apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  labels:
      type: platform
spec:
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.1.2
    helm:
      valueFiles:
      - $values/apps/templates/alloy/values.yaml
  - repoURL: https://github.com/MrHenryD/argo-apps-template/
    targetRevision: main
    ref: values
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 30s
        factor: 2
    syncOptions:
    - CreateNamespace=false
