apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
      type: platform
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 27.25.0
    helm:
      valueFiles:
      - $values/apps/templates/prometheus/values.yaml
  - repoURL: https://github.com/MrHenryD/argo-apps-template/
    targetRevision: main
    ref: values
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 30s
        factor: 2
    syncOptions:
    - CreateNamespace=false
